#!/usr/bin/env bash
set -euo pipefail

DEFAULT_BASE_URL="https://grist.numerique.gouv.fr/"
ENV_FILE="$HOME/.grist_org_visualizer_env"

escape_single_quotes() {
  printf "%s" "$1" | sed "s/'/'\"'\"'/g"
}

detect_shell_profile() {
  if [[ "${SHELL:-}" == *"zsh"* ]] || [[ -n "${ZSH_VERSION:-}" ]]; then
    echo "$HOME/.zshrc"
    return
  fi
  if [[ "${SHELL:-}" == *"bash"* ]] || [[ -n "${BASH_VERSION:-}" ]]; then
    echo "$HOME/.bashrc"
    return
  fi
  echo "$HOME/.profile"
}

prompt_required() {
  local prompt="$1"
  local secret="${2:-false}"
  local value=""
  while [[ -z "$value" ]]; do
    if [[ "$secret" == "true" ]]; then
      read -r -s -p "$prompt" value
      echo
    else
      read -r -p "$prompt" value
    fi
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    if [[ -z "$value" ]]; then
      echo "Valeur obligatoire, merci de réessayer."
    fi
  done
  printf "%s" "$value"
}

prompt_with_default() {
  local prompt="$1"
  local default_value="$2"
  local value=""
  read -r -p "$prompt" value
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  if [[ -z "$value" ]]; then
    printf "%s" "$default_value"
    return
  fi
  printf "%s" "$value"
}

status_line() {
  local name="$1"
  if [[ -n "${!name:-}" ]]; then
    echo "OK  - $name"
  else
    echo "KO  - $name"
  fi
}

echo "Configuration des variables Grist pour grist-org-visualizer"
echo

GRIST_API_KEY="$(prompt_required "GRIST_API_KEY (obligatoire) : " true)"
GRIST_DOC_ID="$(prompt_required "GRIST_DOC_ID (obligatoire) : ")"
GRIST_BASE_URL="$(prompt_with_default "GRIST_BASE_URL (optionnel) [${DEFAULT_BASE_URL}] : " "$DEFAULT_BASE_URL")"

{
  echo "# Generated by grist-org-visualizer setup"
  printf "export GRIST_API_KEY='%s'\n" "$(escape_single_quotes "$GRIST_API_KEY")"
  printf "export GRIST_DOC_ID='%s'\n" "$(escape_single_quotes "$GRIST_DOC_ID")"
  printf "export GRIST_BASE_URL='%s'\n" "$(escape_single_quotes "$GRIST_BASE_URL")"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

PROFILE_FILE="$(detect_shell_profile)"
SOURCE_LINE='[ -f "$HOME/.grist_org_visualizer_env" ] && . "$HOME/.grist_org_visualizer_env"'
MARKER="# grist-org-visualizer env"

touch "$PROFILE_FILE"
if ! grep -Fq "$SOURCE_LINE" "$PROFILE_FILE"; then
  {
    echo
    echo "$MARKER"
    echo "$SOURCE_LINE"
  } >> "$PROFILE_FILE"
fi

# Available immediately in this script process.
. "$ENV_FILE"

echo
echo "Vérification dans le shell courant :"
status_line "GRIST_API_KEY"
status_line "GRIST_DOC_ID"
status_line "GRIST_BASE_URL"

echo
echo "Persisté dans : $ENV_FILE"
echo "Profil mis à jour : $PROFILE_FILE"
echo
echo "Pour rendre les variables disponibles dans votre terminal actuel :"
echo "source \"$PROFILE_FILE\""
